[package]
name = "iroh-willow"
version = "0.14.0"
edition = "2021"
readme = "README.md"
description = "willow protocol implementation for iroh"
license = "MIT/Apache-2.0"
authors = ["n0 team"]
repository = "https://github.com/n0-computer/iroh"

# Sadly this also needs to be updated in .github/workflows/ci.yml
rust-version = "1.75"

[lints]
workspace = true

[dependencies]
anyhow = "1"
derive_more = { version = "1.0.0-beta.1", features = ["debug", "deref", "display", "from", "try_into", "into", "as_ref"] }
ed25519-dalek = { version = "2.0.0", features = ["serde", "rand_core"] }
flume = "0.11"
iroh-base = { version = "0.14.0", path = "../iroh-base" }
iroh-metrics = { version = "0.14.0", path = "../iroh-metrics", optional = true }
num_enum = "0.7"
postcard = { version = "1", default-features = false, features = ["alloc", "use-std", "experimental-derive"] }
rand = "0.8.5"
rand_core = "0.6.4"
serde = { version = "1.0.164", features = ["derive"] }
strum = { version = "0.25", features = ["derive"] }
bytes = { version = "1.4", features = ["serde"] }
hex = "0.4"
thiserror = "1"
tracing = "0.1"
tokio = { version = "1", features = ["sync"] }

# fs-store
redb = { version = "2.0.0" }
tempfile = { version = "3.4" }

# net
iroh-net = { version = "0.14.0", optional = true, path = "../iroh-net" }
tokio-util = { version = "0.7", optional = true, features = ["codec", "io-util", "io"] }
tokio-stream = { version = "0.1", optional = true, features = ["sync"]}
quinn = { version = "0.10", optional = true }
futures = { version = "0.3", optional = true }
self_cell = "1.0.3"
zerocopy = { version = "0.8.0-alpha.7", features = ["derive"] }

[dev-dependencies]
iroh-test = { path = "../iroh-test" }
rand_chacha = "0.3.1"
tokio = { version = "1", features = ["sync", "macros"] }
proptest = "1.2.0"
tempfile = "3.4"
test-strategy = "0.3.1"

[features]
default = ["net", "metrics"]
net = ["iroh-net", "tokio/io-util", "tokio-stream", "tokio-util", "quinn", "futures"]
metrics = ["iroh-metrics"]
